# Generated by Django 3.2.6 on 2021-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotList_Day',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rank', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HotList_Month',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rank', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HotList_Week',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rank', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HotList_Year',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rank', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('project_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('wx_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
                ('collections', models.JSONField()),
            ],
        ),
    ]
