# Generated by Django 3.2.6 on 2021-11-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataTransmission', '0002_auto_20211111_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='readHistory',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='collections',
            field=models.JSONField(null=True),
        ),
    ]
